services:
  web-service:
    image: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/health-api:v5
    container_name: web-app2
    environment:
      - REDIS_HOST=redis
    ports:
      - "80:7000"
    depends_on:
      - redis
  
  redis:
    image: redis:7-alpine
    container_name: redis-backend

